### ISSUE TITLE
Create Development environment defaults to Contoso

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#1]
# Lab: 00
#### Step: 02

Your Dev environment should now show in the list of Environments. This typically is named MOD Administrator’s Environment. For the rest of this course when it says Dev environment it will be this environment.

Description of issue
The name of my Environment is Contoso (default) and I do not seem to be able to create another

Repro steps:

1.
1.
1.

**Comment by VitalyMCT** [comment]
@davidyack  Same issue here. I am following instructions as specified.

This is clearly an issue. Easy to repro with Skillable ALH.

Can you please investigate?
