### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#101]
Can you please set up GitHub Pages for this repo?

Going to https://microsoftlearning.github.io/PL-500T00-Microsoft-Power-Automate-RPA-Developer currently produces a 404.

GitHub Pages is references in the Instructor Guide. 

It's also standard in most Microsoft Learning repos. Example: https://microsoftlearning.github.io/PL-300-Microsoft-Power-BI-Data-Analyst/

**Comment by ephiax20** [comment]
Hi, I've provisioned the Github Pages for this repo.  It looks empty at the moment, but I think it should automatically populate when related Issue #102 is resolved.

**Comment by VitalyMCT** [comment]
@ephiax20 Issue is still open, in that there are no working GitHub Pages (although the site is provisioned now, yes). Same link as in issue description: https://microsoftlearning.github.io/PL-500T00-Microsoft-Power-Automate-RPA-Developer will allow you to verify.

Can you please re-open the issue, verify using the link provided and then close once resolved?

Also, MOC repos with GitHub Pages have them in readme. Can the same be done here please?

**Comment by ephiax20** [comment]
@VitalyMCT Ahh ha, I just found the Pages template code was looking for Content in /Instructions/Labs not /Instructions - So it should be fixed now.
