### ISSUE TITLE
Missing Lab Numbers and Names

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#102]
This is a global issue that impacts all labs in this course. The course numbers and names are missing from the Markdown content and thus from display in ALHs such as Skillable (they are only present in metadata, which is invisible). The impact is that attendees have no way of telling which lab they are doing. 

Example below:

![image](https://user-images.githubusercontent.com/1765732/195148847-cff6f927-fd3d-4e07-9cf4-7f0551321d5f.png)

Here's an example of the desired result, using [PL-300 repo ](https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/Instructions/01-prepare-data-with-power-query-in-power-bi-desktop.md)as an example:

![image](https://user-images.githubusercontent.com/1765732/195148647-37353b5f-e520-46ae-88c8-ad3a5ad97b5a.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by VitalyMCT** [comment]
@MOC-Labs-Review @ephiax20 

This issue is still present the same as before. 

The referenced commit only adjusts metadata.

Please review the issue description.

**Comment by ephiax20** [comment]
Hey @VitalyMCT I've updated Title Headings on all the Labs in PL-500 now.  Please check & see the latest commits

**Comment by VitalyMCT** [comment]
@ephiax20 Looks good now, thanks.
