### ISSUE TITLE
Setup my lab environment => Exercise 2 => New workflow

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#105]
This screen now appears after executing Exercise 2, Task 1, Step 1:

![image](https://user-images.githubusercontent.com/1765732/195366201-e491dfff-c53e-4e1a-8f98-f3aa43394b4d.png)

Please amend the instructions accordingly.

**Comment by julians1966** [comment]
This country popup is about adding the user to a marketing list. If you change to a different country, you can see different options to opt out. As the tenants are US based, I advise students to leave as United States and not change anything and just click Accept

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue

**Comment by VitalyMCT** [comment]
@MOC-Labs-Review Which ALH are you using?

**Comment by ephiax20** [comment]
I found this issue on Skillable ALH and have updated the instructions to include clicking Accept.

**Comment by VitalyMCT** [comment]
@ephiax20  

Same as the other 2 related tickets - the instructions need to provide guidance to attendees about country selection. It seems at least some aspects would only work if they keep it at US, which seems to be default in Skillable (this also needs research / validation).
