### ISSUE TITLE
Setup my lab environment => Exercise 3 => New workflow

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#106]
This is similar to some of the other issues filed around the platform now prompting the user for a country/region:

![image](https://user-images.githubusercontent.com/1765732/195377238-54697565-9f4c-4d1c-94e5-ae9b21669040.png)

**Comment by julians1966** [comment]
This country popup is about adding the user to a marketing list. If you change to a different country, you can see different options to opt out. As the tenants are US based, I advise students to leave as United States and not change anything

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue

**Comment by VitalyMCT** [comment]
@MOC-Labs-Review Which ALH are you using?

**Comment by ephiax20** [comment]
I found this issue on Skillable and have updated the instructions to include clicking 'Get started'

**Comment by VitalyMCT** [comment]
@ephiax20 What about the country/region selection? I think the instructions should guide the attendees through that too.
