### ISSUE TITLE
Lab 1 => Exercise 6 => Tasks 2 and 3 => Navigation in new browser tabs

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#113]
Regarding the instruction segment in the screenshot below. 

The current behavior for make.powerautomate.com is to open flows for editing in new browser windows. The instructions assume the editing happens in an existing tab.

This happens in Task 2, Task 8. As a result, Task 2 step 11 no longer applies, it should be replaced with a step that instructs the reader to close the current browser tab. The reader can then continue Task 3 in the original browser tab.

![image](https://user-images.githubusercontent.com/1765732/195422546-c593c15b-6bd7-4f0a-abf4-a01f90c79a35.png)

**Comment by davidyack** [comment]
Step 11 advises them to not navigate away from the solution because the next task has them continue using the solution components list by selecting Cloud flows

**Comment by VitalyMCT** [comment]
@davidyack That's my point, the instructions do not match the current UI, starting with Step 10. There are 2 tabs open instead of 1, thus the back button does not do what the instructions expect and then the subsequent steps also break down. 

Please try it out in the current UI and you will see it.

**Comment by davidyack** [comment]
@VitalyMCT the difference is in the portals, Ex6 Task 1 has you use make.powerapps.com which does not open the flow in a new tab.  make.powerautomate.com opens flows in another tab
