### ISSUE TITLE
Lab 2 => Account Number vs. Loan Number

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#116]
In a few places in this lab the Loan Number (label in app) is called Account Number in instructions. Example below.

Please update all references in this lab and other labs as appropriate.

Instructions (one example only):

![image](https://user-images.githubusercontent.com/1765732/195738674-568b1339-1d58-4cd9-94f2-68b59b4fe37d.png)

App:

![image](https://user-images.githubusercontent.com/1765732/195738783-2045e498-3cf7-444c-aca2-2fed13a08135.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull request #138.
