### ISSUE TITLE
Lab 2 => Exercise 1 => Task 3 => Variable type

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#117]
Data type names have changed in the current version Power Automate Desktop, from "string" to "text".

In instructions:

![image](https://user-images.githubusercontent.com/1765732/195739559-92a22a2f-74b5-4caa-8f9d-c4e57d99d7f1.png)

In UI:

![image](https://user-images.githubusercontent.com/1765732/195739641-9f999896-3456-4eb2-a61d-89a9f66b0c61.png)

Please update this and all other references as required.

**Comment by MOC-Labs-Review** [comment]
MOC Labs review has solved this issue with pull request #137.
