### ISSUE TITLE
Lab 2 => Step sequencing gets reset

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#120]
Not sure if the intent was to create continuous sequencing or whether a new Task number is missing and the sequence was intended to restart for that task. Please apply one of these 2 fixes.

![image](https://user-images.githubusercontent.com/1765732/195742029-31060949-086d-4a4f-b667-59c9f94bc8d9.png)

**Comment by VitalyMCT** [comment]
Same issue occurs again a few steps down. Please review and fix in all instances in this and other labs.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by ephiax20** [comment]
This is intended behaviour, the steps 1-15 are the steps to be reproduced whilst the Recorder is enabled, sort of separated from the actual Lab steps. In the Lab Instructions, it renders those steps as 1) 2) etc. 

![image](https://user-images.githubusercontent.com/116392278/201326671-2388087d-878e-4190-9419-52bf03583c44.png)

The final steps in the Task are numbered 16, 17 and 18. But Skillable is not picking this numbering up for some reason.

**Comment by ephiax20** [comment]
Steps 16, 17 and 18 in this case- appears to be a bug on Skillable side, I've logged a Support ticket about this. Github has 16, 17 and 18 but SKillable resets the numbering to 1, 2, 3 for those Steps.

**Comment by VitalyMCT** [comment]
@ephiax20 It's very confusing to both attendees and MCTs. Can the steps at least be indented correctly in the Markdown? Use different numbering scheme, such as a), b), c) etc., or i) ii) iii)? I think some kind of a separation is appropriate for this scenario.

Plus in platforms like Skillable these extra steps lack checkbox tracking.
