### ISSUE TITLE
Set up my lab environment => Exercise 3

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#123]
Regarding

> If you receive a warning about a duplicate install, go ahead and accept the install. 

It appears that in the official ALH VM image Power Automate desktop may already be installed via the Microsoft Store. I think we are creating a confusing situation for the attendees with this side-by-side Microsoft Store and MSI installer deployment. 

We are trying to instill Power Automate best practices and I can't see how this is one of them. It gets even more confusing in a later lab when we ask attendees to update the version that was deployed from Microsoft Store.

Can the instructions and VM please be standardized on a single installation method for Power Automate desktop?

**Comment by VitalyMCT** [comment]
Update: this relates to https://github.com/MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer/issues/83

**Comment by VitalyMCT** [comment]
Below is the screenshot of the patch within Skillable ALH that I was referring to above by

> It gets even more confusing in a later lab when we ask attendees to update the version that was deployed from Microsoft Store.

It's in Lab 2.

![image](https://user-images.githubusercontent.com/1765732/196011013-80409544-56e1-405c-bf8a-09969c7f04a7.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by ephiax20** [comment]
Hi @VitalyMCT I believe it is a good learning experience for the Course Attendees to go through the Power Automate Desktop install experience as it's something they might need to do later in real life and out of the lab setting.  Following the steps works as presented and I got the similar error/warning in Lab 2 and updated Power Automate as the warning indicated, so the Instructions themselves are not invalid or incorrect.  Therefore, I won't recommend any changes for this issue.

**Comment by VitalyMCT** [comment]
@ephiax20 I agree that going through the install experience could be valuable, however, that's not the issue outlined in this ticket. 

The issue is that the VM + instructions are trying to force a deployment configuration on attendees that's unsupported by Microsoft's Power Automate PG. It makes zero technical sense to do that.

Please see https://github.com/MicrosoftDocs/power-automate-docs/issues/820 for details.

**Comment by ephiax20** [comment]
Draft instructions for Exercise 3, instructions to upgrade Power Automate to latest version.  We are reviewing this internally.



Exercise 3 - Updating Power Automate 

Power Automate is included in Windows 11 by default but it may need to be updated to the latest version.

1.  Open the Microsoft Store and select Library 
from the left-hand navigation.

2.  Search for Power Automate and click **Update**.

3.  When the update is finished, click **Open**.

Note: Further updates may be required. Refresh the Power Automate page in the Microsoft Store and select Update again.

https://www.microsoft.com/store/productId/9NFTCH6J7FHV

4.  When Power Automate opens, login using your Microsoft 365 Credentials. Click **Next** and **Get started**.

Optional: Click **Start tour** and go through the welcome prompts to get a feel for the application.

5.  From the Environments list, select your Dev environment.

6.  Close Power Automate for now but notice it will stay running in the system tray.

**Comment by ephiax20** [comment]
@VitalyMCT I found an issue down the line with this method. The Microsoft Store install evidently does not install the machine-runtime to register the Machine to run Desktop Flows from Cloud, this turns up in the next module. So, it looks like either way, another install would be required. I will continue to review the Course with this in mind.

**Comment by VitalyMCT** [comment]
@ephiax20 In that case your findings show that the official Microsoft documentation around deployment is incorrect (even after the update). I would recommend you perform the following action items:

1) Uninstall the Windows Store installation from the standard VM image for this course. There is a whole lot of reasons to avoid side-by-side deployment the instructions currently try to force, including: it's unsupported by Microsoft, it's confusing to the attendees and it adds zero value in the context of this course compared to simply using the MSI deployment.
2) Open a GitHub ticket for the Microsoft documentation team (same as I did with the other issue) and ask them to correct the documentation issue you found.
3) Regarding "_Power Automate is included in Windows 11 by default_". According to https://powerautomate.microsoft.com/en-us/power-automate-and-windows-11/ that's not quite accurate. Power Automate is only included on machines using a Microsoft account. The lab VMs are using a local account.

**Comment by ephiax20** [comment]
@VitalyMCT Regarding 3. It is accurate. https://learn.microsoft.com/en-us/power-platform-release-plan/2021wave2/power-automate/power-automate-availability-windows#:~:text=Users%20of%20the%20new%20Windows%2011%20will%20have%20Power%20Automate%20for%20desktop%20in%20their%20machines%20by%20default.  It is installed by default. But without the machine-runtime part enabled. You need a Microsoft account to log into it to make any use it.  We give a Microsoft account in the lab VMs.

In this screenshot, on the left is 'Power Automate' the app which is installed by default on Windows 11. On the right is the machine-runtime which is waiting for Connections from Cloud flow to call it.
![image](https://user-images.githubusercontent.com/116392278/203330519-1f6ca4b0-d543-4490-8064-08a4b0da019f.png)

In this case, it's not a duplicate install. It is two different parts of the same application as you can see from this screenshot of the installer:-

![image](https://user-images.githubusercontent.com/116392278/203331035-4725c7ce-6f6a-4fdc-83ed-56edbd3d618e.png)

**Comment by ephiax20** [comment]
https://learn.microsoft.com/en-us/power-automate/desktop-flows/getting-started-windows-11#:~:text=Windows%2011%20allow%20users%20to%20create%20automations%20through%20the%20preinstalled%20Power%20Automate%20app.

**Comment by VitalyMCT** [comment]
@ephiax20 Item 3 is from Microsoft's main Power Automate website - i.e. the link I provided. I would be quite surprised if it's incorrect. The 1st link you provided has a note about it not being maintained anymore and the 2nd link makes no mention of deployment defaults.

![image](https://user-images.githubusercontent.com/1765732/203363983-661ff027-74c5-4f8c-b2d9-c3e007cd9c88.png)

Also, the "_we give a Microsoft account in the lab VMs_" does not reflect the ALH setup. The accounts provided are "work or school accounts" on the auto-provisioned Microsoft 365 tenant, not "Microsoft accounts". These are completely different account types. Quoting from the link you posted (https://learn.microsoft.com/en-us/power-automate/desktop-flows/requirements#sign-in-account-comparison):

![image](https://user-images.githubusercontent.com/1765732/203365832-c64ebd3d-a250-44cf-99ec-d1f9b492ffc3.png)

Putting the entire Windows 11 defaults aspect aside for the moment, I am puzzled as to the reason you believe the Power Automate installation is not duplicate. The instructions themselves literally say "duplicate install", as does the Power Automate installer itself:

> Check Install the Power Automate for desktop to build desktop flows (if unchecked) and take the default options for the rest. Check "By selecting 'Install', you agree to Microsoft's terms of use". If you receive a warning about a **duplicate install**, go ahead and accept the install.

The instructions are currently forcing the attendees into this unsupported deployment topology in the first few labs steps. How is that beneficial?

The fix here for all these issues & the ever-growing set of complex workarounds in the instructions is to simply follow Microsoft's PG guidance, i.e. my recommendation number 1. If for any reason that's too complicated logistically, just ask attendees to uninstall the Windows store deployment during lab setup. Is there any reason that's not being actioned? If so, what is that reason?

I do think there are still some assumptions being made here around Power Automate deployments, so recommendation number 2 is also important if you want attendees to have a reliable and predictable lab experience.
