### ISSUE TITLE
Lab dependencies?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#126]
A question attendees always have in any course is: 

_What happens if I skip or do not have time to complete a particular lab? Can I still do subsequent labs?_

With this in mind, are there any dependencies between the 7 labs in this course? 

If so, let's clarify the specifics of these dependencies in the instructions so the attendees can manage them. Otherwise, let's add a note to the effect as well.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by skulthm-ms** [comment]
Thank you @VitalyMCT. The labs are designed to be completed in a sequential manner and as one realistic scenario. That being said. We hear your feedback that sometimes issues happen and knowing the dependencies can be really helpful. We will include it in our future updates asap.
