### ISSUE TITLE
Time estimates

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#127]
I think attendees and MCTs need time estimates for each lab. The labs have varying levels of complexity and time requirements. Both groups of stakeholders need to know those time requirements for effective scheduling.

Please see https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/Main/Instructions/01-prepare-data-with-power-query-in-power-bi-desktop.md for an example of timing information in another MOC course.

It's just a matter of Microsoft estimating the timing and publishing it within the lab instructions. An alternative would be to publish them in the MCT Trainer Prep Guide. I think having timing details included in lab instructions would be better because they would be accessible to attendees and be easier to change based on community feedback.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by skulthm-ms** [comment]
Great suggestion Vitaly. We unfortunately don't have this data from our side for all the labs in this course but as you mentioned, it will be even better if its coming from the community with averages/ranges across diverse audiences. Would you be willing to share your timings in MCT central to start?

**Comment by skulthm-ms** [comment]
I am closing this for now. Please share your timing if you feel comfortable doing so.
