### ISSUE TITLE
Lab 1 => Exercise 2 => Task 1 => Step 7 - OAuth connection issue

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#135]
The following step is not working for many if not all of of our attendees this week:

![image](https://user-images.githubusercontent.com/1765732/196277951-c6b66e07-cb7e-4fc4-99ea-c31c9d50f100.png)

It's throwing an OAuth error, similar to this:

![image](https://user-images.githubusercontent.com/1765732/196278172-61e9d4ee-5a39-4da3-bb00-d91bbe8a1e7e.png)

We tried the patch workaround posted on Skillable, without success:

![image](https://user-images.githubusercontent.com/1765732/196278288-6ca54443-fa2b-4b6b-9141-50f859b21c75.png)

We even tried fixing the connection from the Connections panel in the portal:

![image](https://user-images.githubusercontent.com/1765732/196278384-31d9b2ae-7aac-4f73-9d27-f76ed26b09b4.png)

After the attempt above the error goes away and the Next button is enabled. However, after clicking it the UI waits a few minutes and then goes back to the same step.

**This issue blocks attendees with completing this exercise in the lab. Please investigate ASAP.**

**Comment by davidyack** [comment]
@VitalyMCT  I was able to reproduce this as well and it seems to be related to the Power Query api that is used.  The same occurs for me with Upload file or Link to existing.  In fact, I see the same error in Dataflows where it uses Power Query. The problem does not exist in all tenants as I'm able to have it work in some.

**Comment by ephiax20** [comment]
I encountered this issue during Lab testing but I found the solution was to log into OneDrive, so the current advice in the instructions is correct. Logging into office.com using the Tenant admin credentials should be enough to get past this point too- but I will re-test it a few times with fresh environments to confirm it..

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by skulthm-ms** [comment]
@VitalyMCT first of all thank you for reporting this. I believe @ephiax20 has re-tested this several times now and the workaround seems to be working. Can you please confirm?
This seems to be out of our control at the learning team.

**Comment by VitalyMCT** [comment]
It's a little too late to be troubleshooting this. This issue impacted deliveries 3 months ago. An investigation and fix would've been useful at that time.
