### ISSUE TITLE
Impact assessment and upgrade of instructions for Power Automate for desktop build 2211

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#178]
A new version of Power Automate for desktop has just been released: https://learn.microsoft.com/en-us/power-platform/released-versions/power-automate-desktop/2211

It includes a significant amount of enhancements and other changes, some of which may impact lab instructions. I am thinking of the new trial workflow as one element that would need closer analysis and possibly updates to instructions (at least screenshots, possibly more).

Per the lab deployment steps the attendees would receive these updates immediately, so the instructions should match this new release to ensure they work well in the live classrooms. Please assess and update the instructions ASAP as appropriate.

**Comment by ephiax20** [comment]
Instructions & several screenshots have been updated in my latest round of testing & relevant updates for this course.  If you find anything specific, please let us know.
