### ISSUE TITLE
Known Issue: Power Automate - Narrow browser window does not show Expression editor

### ISSUE THREAD

**Issue by ephiax20** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#181]
# Lab: 3
#### Step: 11, 16, 18, 25

If your browser window is narrower than approximately 1,400 pixels- in a Power Automate Cloud Flow, the standard **Dynamic content** and **Expression** editor pane is not visible.

Repro steps:

1. Change the width of the Browser to see the difference.

![image](https://user-images.githubusercontent.com/116392278/202741997-b2c58eda-95f1-41f1-8fb3-afa2199d6eb3.png)

Workaround: Zoom the Browser out to 90% or make the window wider to reveal the expected Dynamic content pop-out with Expression editor.

![image](https://user-images.githubusercontent.com/116392278/202742226-6d81b76e-61fd-4be3-909d-ae5892c54e63.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by ephiax20** [comment]
@MOC-Labs-Review can you replicate the issue if you make your browser window smaller?? I can replicate this every time.  However, enabling Experimental features in Power Automate settings resolves the issue so this will be fixed in GA eventually.

**Comment by skulthm-ms** [comment]
I am closing this as we added a note in the content in case it happens.
