### ISSUE TITLE
issue in Lab 2 - Build Desktop Flows Module 2 - Desktop Flows

### ISSUE THREAD

**Issue by gituser1432** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#199]
# Module: 02
### Exercise : 02
###Task: 2
#### Step: 15

Description of issue
unable to get dynamic value for "get ui element on web page".Job number is changing everytime we add new record but after recording steps its unable to capture changed job number and throw error.

https://github.com/MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer/blob/master/Instructions/L02/Lab02_Build_Desktop_Flow.md 

i. Go to the Request Inspection page.

vi. Right click on the Job Number and select Extract element value | Text: (“your job number here”). Remember the Job number.

Repro steps:
https://github.com/MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer/blob/master/Instructions/L02/Lab02_Build_Desktop_Flow.md
![lab issue](https://user-images.githubusercontent.com/127949719/225298938-8c7701a8-dffe-420d-9823-1d5f3861f413.jpg)

1.
1.
1.

**Comment by jamarx2** [comment]
Proposed workaround:
1. Stop recording after clicking the "Request Inspection" step.
2. Manually add "Extract data from web page" and capture the Job Number value. (In Exercise 3, Step 12, we'll edit the step to replace the hard value with the variable ).
4. Start recording again - first step should be to click the "Inspection Results" anchor at the top.
5. Finish steps as published - you'll need to do a little manual clean up, but it should be obvious once you see it. 
6. Proceed with Exercise 3 to properly replace hard values with variables.

**Comment by davidyack** [comment]
The issue is the recorder is adding a compare to the table cell value on the selector - this will never match on future job numbers

You can resolve by changing from comparing the value to using the Ordinal 1 for the 2nd cell in the table row 

![image](https://github.com/MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer/assets/365974/a37149d6-9a15-4278-a86c-65960f3e00fe)
