### ISSUE TITLE
Lab files target unclear

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#2]
# Lab/Demo: 00
### Step: 01 - Copy the lab resources folder to C:\Labs

Description of issue
Is the target for the C:\Labs directory the VM just created or the Lab or local workstation?

Repro steps:

1.
1.
1.

**Comment by davidyack** [comment]
Hi Chris, the lab files just have to be on the same place on the machine you run Power Automate Desktop and the VM you deploy in the lab for unattended execution. For simplicity, c:\Labs on both but you can use any path as long as you use the same in both places.

**Comment by chris-utter** [comment]
Thanks David, I wasn’t sure. Any updates on getting the bank app to install properly? Thanks!

Chris Utter
Worldwide Learning
Microsoft
________________________________
