### ISSUE TITLE
Setup Environment Lab - Ex 3 - Power Automate not updating - Skillable 

### ISSUE THREAD

**Issue by arnoldvilleneuve** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#200]
# Module: 01
#### Step: 03

Description of issue

Power Automate Desktop will not update. 

Try again! 

![image](https://user-images.githubusercontent.com/1082625/225997585-cf393a4d-efc2-442d-9265-8fce89b94499.png)

Workaround looks like it needs Skillable to get involved. 

https://learn.microsoft.com/en-us/troubleshoot/windows-client/group-policy/archived-application-cant-be-restored

In these cases, you have to contact your system administrator to obtain an updated version of the application. The information in this article helps you to do this.

**Comment by ephiax20** [comment]
Hi, does it complete the update if you restart the Microsoft Store, or even reboot the entire VM? You may find it needs to update then update again, I found this when testing.

Otherwise, if you haven't already, please use the **Submit feedback** link.

**Comment by arnoldvilleneuve** [comment]
You are indeed correct and this is what is suggested here. 

https://learn.microsoft.com/en-us/troubleshoot/windows-client/group-policy/archived-application-cant-be-restored

I wanted Skillable to witness the issue so that they could update their lab instructions to reflect the issue. This will be important to Students that are doing the labs after the course event is over and they are trying to take advantage of the ILT benefits by redoing the labs over the next 30 to 180 days. 

Thank you Skillable for the great follow up.

**Comment by ephiax20** [comment]
I can get the instructions updated with a Note about this 👍🏻

**Comment by arnoldvilleneuve** [comment]
Thank you Ephiax20. 

Does anyone use their real name around here?

**Comment by arnoldvilleneuve** [comment]
Ephiax20

Below are some comments from a fellow MCT whom I have a great deal of respect for. I'm reviewing the course now for a Learning Partner prior to the course running because they are very concerned about the event being successful. 

Can you please let me know if the course content creators addressed Vitaly's comments from last October:

Thank you: Arnold 

Replied on October 16, 2022 by Vitaly LivshitsQuote from Vitaly Livshits "I hear you. I wonder if anyone has delivered this course with its labs yet. My guess based on the feedback in GitHub and the lack of responses here is that the answer is either "no" or "very few".If someone from Microsoft is reading this thread, can you please ping the course author(s) to perform some much-needed maintenance on the labs? The MCT community has no ability to contact the right people beyond GitHub (and IMO neither should MCTs be in the business of chasing these lab issues down ... teaching is challenging enough as it is).In the current state MCTs would simply be declining to teach PL-500. That would be a lose-lose proposition for everyone concerned. I think this course has the potential to be outstandingly popular. It just a needs TLC around the labs. Thank you!"Update...

So I am teaching my first session of this course starting Monday. There is simply no evidence of any type of QA around the lab instructions. 

Typos. Lots and lots and lots of typos. Thanks to one fellow MCT who went before me and filed dozens upon dozens of PRs to fix some of them.
Missing lab names and numbers (!)
Missing steps
Weird code formatting
Step numbering that gets reset mid-way
Complex dependencies between labs that are undocumented
All kinds of out-of-date information, including references to old Power Platform UI's
Information that's inapplicable when inside an ALH environment
Markdown glitches or inconsistent use of Markdown
Etc.

And then once ALHs integrate these instructions into their platforms they also skip QA (because ... budgets! QA is expensive!). So now there are inadvertently 2 sets of glitches for us to troubleshoot: the ones in GitHub and the ones from ALHs. 

As a result of all this things are incredibly confusing for attendees to complete. On top of this, ALHs, MCT Support Forum and GitHub folks are playing "not my department" pingball. No one wants to take ownership of the problems. Guess who the buck stops with? 

Now MCTs are supposed to stand in front of the class, smile, make the best of this situation and make Microsoft, LPs, ALHs and themselves look great. Fun times!

**Comment by ephiax20** [comment]
Hi Arnold,

I have added a further note in the instructions about updating the Microsoft Store and rebooting the VM to ensure everything is as up to date as possible which should lead to Power Automate being able to update. 

There is a WIP recommendation for Microsoft/Skillable to update the VM images used in this course, which will mitigate the requirement to update the Microsoft Store and Power Automate applications. 

As such, I am marking this issue as Closed. 


The comments you quote from Vitaly L from Oct 2022 is right before this course, PL-500, was fully tested all the way through and there were over 100 commits made, fixing the typos, numbering and specific issues Vitaly had raised. 

If you have any further feedback on the course content, it is most welcome. 


Thanks,
Simon

**Comment by arnoldvilleneuve** [comment]
ThxGet Outlook for AndroidFrom: Simon E ***@***.***>Sent: Tuesday, March 21, 2023, 12:23 p.m.To: MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer ***@***.***>Cc: Arnold Villeneuve ***@***.***>; Author ***@***.***>Subject: Re: [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer] Setup Environment Lab - Ex 3 - Power Automate not updating - Skillable  (Issue #200)
Hi Arnold,
I have added a further note in the instructions about updating the Microsoft Store and rebooting the VM to ensure everything is as up to date as possible which should lead to Power Automate being able to update.
There is a WIP recommendation for Microsoft/Skillable to update the VM images used in this course, which will mitigate the requirement to update the Microsoft Store and Power Automate applications.
As such, I am marking this issue as Closed.
The comments you quote from Vitaly L from Oct 2022 is right before this course, PL-500, was fully tested all the way through and there were over 100 commits made, fixing the typos, numbering and specific issues Vitaly had raised.
If you have any further feedback on the course content, it is most welcome.
Thanks,
Simon
