### ISSUE TITLE
Lab 4, Exercise 2: Error with Get a row by ID

### ISSUE THREAD

**Issue by jamarx2** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#202]
# Lab 4: Custom Connectors
#### Step 6: Select Loans for Table name, click on the Row ID field and select LoanID from the dynamic content pane.

Description of issue
Working through the steps as written, the test fails at "Get Loan" (Get a row by ID action).
While debugging, I noticed that the output from the Lookup Loan Number step has a loaned value of " 6f054d95-c4d3-ed11-a7c7-000d3a8fbb5c" (notice the leading space). This leading space causes the flow to fail at the Get Loan step.

Repro steps:
1. Create the flow as written in the exercise.

Proposed solution:
1. At step 6, use a Trim expression with loanID, which works like a charm.

**Comment by skulthm-ms** [comment]
Thank you jamarx2. Labs are updated now.
