### ISSUE TITLE
Lab 2 Fabrikam Site crashes intermittently

### ISSUE THREAD

**Issue by DanePillay-nel** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#203]
# Module: 02
#### Step: 06

Description of issue
The lab requires students to browse the Fabrikam website and record the basic interactions of checking inspection results.
But the site keeps crashing resulting in the Powe automate workflow to continuously crash also.

![image](https://user-images.githubusercontent.com/13525534/233183273-eb3ed51b-d342-4f61-970c-a01e3f339182.png)

**Comment by DanePillay-nel** [comment]
Hi Glen,

This really frustrated me. Because it worked during prep as well. And it also worked for some students but suddenly stopped for me and another student. Worst part was it was intermittent as well. And because this was an azure hosted site and nothing on the local vm there was nothing I could do. Unfortunately, this wasn't acknowledged by Ms or the contributors on this repo.
I hope we come up with something before presenting this again. Good luck


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by skulthm-ms** [comment]
We apologize for the crashing. We were looking at the issue and we believe we got it fixed now. I am going to close this for now, but please let us know if you face this issue again.
