### ISSUE TITLE
Lab 5 Exercise 2 UI changes, steps not needed

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#208]
# Module: 05
#### Step: 24 and 35

Description of issue
Building block updates, these steps are not needed anymore
24 Select the Get attachment (V2) action from the Office 365 Outlook connector.
35 Select the Initialize variable action from the Variable connector.

Repro steps:

1.
1.
1.

**Comment by skulthm-ms** [comment]
Thank you Molenaar. We just pushed an update please check it out.
