### ISSUE TITLE
Issue with last lab, Deploy Solution

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#213]
# Lab 7 - Deploy Solution
## Exercise #5 - Import Solution

I think this lab needs to be changed;   In the lab you Export your solutions as Managed..and then in Exercise 5 it tells you to import them, but you import them in the same Environment...  And that won't work, since you can't import a solution if it already exists in this case.

I've had students create a new Environment, and do the imports there...but now the difficulty is the Azure VM is connect to a Machine Group in the "Test" environment and not one in this new environment.

Another option would be to NOT do the Export/Import, but just keep the same solution / same environment...and then create the Machine Group for the Azure VM...but there will need to be the instructions on how to have the Desktop flow run in the Machine Group instead of the 'regular' lab VM they've been using all week.

**Comment by tylerfarmer1** [comment]
Good grief, blame it on lack of sleep.

**Comment by davidyack** [comment]
:) no worries
