### ISSUE TITLE
Lab 0 Exercise 5 Copy Lab Resources .NET problem

### ISSUE THREAD

**Issue by Skillable-DavidBehymer** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#218]
Lab 0: Setup the lab environment

Exercise 5 - Copy Lab Resources 

With the newest VM, these steps are no longer working properly as currently written.

**Comment by ephiax20** [comment]
@Skillable-DavidBehymer can you give any more specifics about the issue you're facing? Is there any error?

**Comment by ephiax20** [comment]
@Skillable-DavidBehymer Replicated the issue. Selecting **Yes** to download .NET installer does nothing.

**Comment by skulthm-ms** [comment]
This should be working now
