### ISSUE TITLE
Not able to create Virtual Machine for Setup the lab environment (PL-500)

### ISSUE THREAD

**Issue by umanhooda** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#225]
# Module: Setup the lab environment
#### Step: 9 to 14

Description of issue
I am not able to find  size in size drop down displayed in screen shots in instruction pane. Selected size from DC series after selecting 'see all sizes'.
Tried with different sizes as well but still getting error messages on validation and not able to create Virtual Machine.
Repro steps:
Setup the lab environment
1.Exercise 4 - Azure account setup
2. follow all instructions till step 9
3. size is not auto populated> selects size from all sizes available
4. Review + create
5. Got error for selected size.

[Pl-500 lab issue.docx](https://github.com/user-attachments/files/15985701/Pl-500.lab.issue.docx)

**Comment by skulthm-ms** [comment]
Azure lab is removed per latest published update
