### ISSUE TITLE
Lab03_Use_Desktop_Flow_from_Cloud_Flow-Exercise 2_Task 02_Step 60

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#227]
# Module: 03
#### Step: 60

An error occurred while running the flow:

"_Problem while executing action 'LaunchEdge': Failed to take control of Microsoft Edge due to a communication failure with the Power Automate web extension._

_Microsoft.Flow.RPA.Desktop.Modules.SDK.Extended.Exceptions.InternalActionException: Unable to take control of Microsoft Edge (communication with the Power Automate web extension failed)_" 

It appears there may be an issue with the Power Automate extension, despite having installed the latest version.

![image](https://github.com/user-attachments/assets/e4aa4222-b4d9-4b97-a8ca-b1a1cc6a6b72)

**Comment by Nimra-Maryam** [comment]
Any Update?

**Comment by maheshkushare** [comment]
Hi @Nimra-Maryam , 

is your issue resolved?

I had same problem, and it got resolved by updating the latest version of Power Automate desktop and runtime. 
I had a version 2.48 where the same issue was there and after update the latest i.e. 2.49 its working fine for me.

**Comment by Nimra-Maryam** [comment]
Yes, the issue was resolved by updating the Power Automate Desktop to the latest version.
Thank you
