### ISSUE TITLE
Lab03_Use_Desktop_Flow_from_Cloud_Flow-Exercise #2_Task # 2_Step 59

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#228]
# Module: 03
#### Step: 59

It is stated in Step 59 to "_Go to the URL and copy the id GUID._ ", however, a valid GUID does not appear in the URL.

![image](https://github.com/user-attachments/assets/d5e318d1-7007-4df4-a964-cd581ebd5c35)

**Comment by NOZYRAMCT** [comment]
Hi @Nimra-Maryam,

you should play the app first to get the ID, you can find the PLAY button on top right of power app editor (under MA user icon)
