### ISSUE TITLE
Funding Manager App setup failure

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#3]
# Lab: 00
#### Step: 03

Description of issue
Setup fails with error. Log file attached
[1G9F3CB5.log](https://github.com/MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer/files/9022027/1G9F3CB5.log)

**Comment by davidyack** [comment]
Did you clone the repo or download the files?

**Comment by chris-utter** [comment]
I downloaded the files

Chris Utter
Worldwide Learning
Microsoft
________________________________

**Comment by chris-utter** [comment]
Hi David,

I tried cloning the repo, same result, here's the log.  Just trying to study for the cert exam.
Thanks for your help!


Chris | Utter
Sr Technical Trainer
Global Technical Learning
***@***.***[A picture containing diagram  Description automatically generated]
