### ISSUE TITLE
Lab02 -> Task #7: Close browser and test -> 'SitePhotos' out put variable empty.

### ISSUE THREAD

**Issue by usreekanthreddy** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#6]
# Module: Instructions
#### Step: 01

Description of issue
'SitePhotos' variable empty after run flow.
Repro steps:

1. Go to Lab02 -> 'Task #7: Close browser and test' in this repo 'https://github.com/MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer'
2. after execute flow observe 'SitePhotos' out put variable empty.

**Comment by davidyack** [comment]
Can you please add a screenshot of your Run JavaScript function step?

**Comment by davidyack** [comment]
Please reopen if you have further info on the problem so we can help diagnose what happened.
