### ISSUE TITLE
Lab 2: 'Power Automate needs an update' error in Exer 1/Task 2/Step 5

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#83]
# Module: 00
## Lab/Demo: 02
Exercise: 01
#### Step: 05

Description of issue

When it tries to open the local/desktop version of Power Automate in this step, I am seeing an error 'Power Automate needs an update' and 'retry' etc. does not allow it to automatically open desktop app.  In Power Automate/settings/updates it says it is at latest version.

Repro steps:

-Follow instructions as-written, using VM from download center.

-It may be there is a bug in the version of the Desktop Power Automate installed from the download link reference3d earlier in the instructions, since I was able to get this functionality to work if I updated through Microsoft Store.  To do this - in MSFT Store, Go to the **Library** section. Find **Power Automate** in the Updates & downloads section click on the corresponding **Update** button.

-Recommend adding this 'note' to the instructions at that point.

**Comment by skulthm-ms** [comment]
Thank you for pointing this out. We are updating the VMs and it should be sorted out in the next few days.

**Comment by VitalyMCT** [comment]
@skulthm-ms Can you please confirm the new VM images were created? Also, were they deployed to ALHs?
