### ISSUE TITLE
Setup my lab environment => Exercise 2 => Create a database for this environment

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#96]
Regarding

> Change the toggle on Create a database for this environment? to Yes.

This toggle is already set to"Yes", at least under the ALH account we are using. Can we please update instructions to either remove this step, or adjust the language to make it clear that it needs to be changed only if it's not set to "yes" already?

**Comment by davidyack** [comment]
If you select trial it is not set to yes, it is only set to yes if you select trial (subscription based).
