### ISSUE TITLE
Setup my environment => Exercise 3 => No Premium trial option

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#98]
Please see screenshot below. How to proceed?

![image](https://user-images.githubusercontent.com/1765732/190039419-b831a083-2d24-4edc-a2ae-f12f4dda80ab.png)

**Comment by davidyack** [comment]
@VitalyMCT  you should see the following with the trial button - perhaps a trial was already active in that tenant?

![image](https://user-images.githubusercontent.com/365974/195261229-b34b21f3-f325-4e36-81bb-3d693f4a63da.png)

**Comment by VitalyMCT** [comment]
@davidyack Still not seeing this after following the instructions top to bottom within the ALH (Skillable), using pre-provisioned ALH accounts. I've just raised it to Skillable support for the folks there to take a look and hopefully repro.

**Comment by davidyack** [comment]
@VitalyMCT that is weird, I did the test also on a ALH (skillable) pre-provisioned last night as well and it was ok

**Comment by VitalyMCT** [comment]
@davidyack I am not sure as to the reason we are seeing different behavior.

Both Skillable support and I can repro it.

Can you please connect with Skillable and get to the bottom of the issue? Ticket number there is 676389.
