### ISSUE TITLE
87 PRs queued up

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-500T00-Microsoft-Power-Automate-RPA-Developer#99]
These have been queued up for 1 week now. As a result, the instructions that are live with ALHs are quite stale and have known issues that have already been rectified in the PRs. 

Can someone with sufficient access to this repo please approve the PRs?

![image](https://user-images.githubusercontent.com/1765732/190040507-5895c948-c578-4b96-a07b-02dff9cea9b6.png)

**Comment by skulthm-ms** [comment]
Thank you. All PRs have been approved.
